[
  ./programs/nix-index.nix
  ./services/nix-index.nix
  ./services/git/nixos.nix
  ./services/hydroxide/default.nix
  ./services/ipfs-cluster/default.nix
  ./security/mitigations.nix
  ./networking/nftables.nix
  ./networking/wireguard-mesh.nix
  ./networking/namespacing.nix
  ./misc/headless.nix
  ./misc/attrmods.nix
]
