[
  ./programs/nix-index.nix
  ./services/nix-index.nix
  ./services/gitfs.nix
  ./services/hydroxide/default.nix
  ./services/ipfs-cluster/default.nix
  ./services/mastodon/default.nix
  ./security/mitigations.nix
  ./system/machines.nix
  ./networking/nftables.nix
  ./networking/wireguard-mesh.nix
  ./networking/namespacing.nix
  ./wayland/swc-launch.nix
  ./misc/headless.nix
  ./misc/attrmods.nix
  ./misc/platform.nix
  ./misc/qemu.nix
]
