#!/bin/bash

enabled_conf=/etc/apparmor/enabled.conf
profiles_dir=/etc/apparmor.d
profiles_sysfs=/sys/kernel/security/apparmor/profiles
cache_dir=/var/lib/apparmor

mkdir -p -m700 "$cache_dir"
chown root: "$cache_dir"
chmod 700 "$cache_dir"
cache=( --cache-loc "$cache_dir" --write-cache --create-cache-dir )

cd "$profiles_dir"
xargs -n1 apparmor_parser "${cache[@]}" -r < "$enabled_conf"

if [[ -e "$profiles_sysfs" ]]; then
	enforce=()
	while read bin
	do enforce=( ${enforce[@]} $(bash -c "ls -1 $bin" 2>/dev/null) )
	done < <(awk '!/\s+\(enforce\)$/ {print $1}' "$profiles_sysfs")
	for p in "${enforce[@]}"; do aa-enforce "$p" >/dev/null; done

	awk '!/\s+\(enforce\)$/ {exit 1}' "$profiles_sysfs"\
		|| { echo >&2 "ERROR: non-enforced profiles are detected"; exit 1; }
fi

exit 0
